[package]
name = "tentris-license-aggregator"
version = "0.1.1"
edition = "2021"
keywords = ["build-script", "licenses", "spdx"]
repository = "https://github.com/dice-group/tentris-license-aggregator"
readme = "README.md"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "^1"
tracing = "^0.1"
cargo-about = "^0.9"
ureq = "^3.3"
krates = "^0.21"
spdx = "^0.13"
serde = { version = "^1", features = ["derive"] }

[dev-dependencies]
serde_json = "1.0.149"
